# Generated by Django 5.2.8 on 2026-05-03 03:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cutless', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeout_sesion', models.IntegerField(blank=True, help_text='Tiempo de inactividad antes de cerrar sesión (en minutos). Déjalo vacío para usar el valor por defecto (30 min). 0 para desactivar.', null=True)),
                ('rol', models.CharField(choices=[('usuario', 'Usuario'), ('admin', 'Administrador')], default='usuario', help_text='Rol del usuario en el sistema', max_length=20)),
                ('tema_preferido', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('auto', 'Automático')], default='auto', help_text='Tema de color preferido', max_length=10)),
                ('tamanio_fuente', models.CharField(choices=[('small', 'Pequeño'), ('normal', 'Normal'), ('large', 'Grande'), ('xlarge', 'Extra Grande')], default='normal', help_text='Tamaño de fuente preferido para facilitar la lectura', max_length=10)),
                ('tutorial_completado', models.BooleanField(default=False, help_text='Indica si el usuario ha completado el tutorial inicial')),
                ('unidad_medida_predeterminada', models.CharField(choices=[('cm', 'Centímetros (cm)'), ('m', 'Metros (m)'), ('mm', 'Milímetros (mm)'), ('in', 'Pulgadas (in)'), ('ft', 'Pies (ft)')], default='cm', help_text='Unidad de medida que se usará por defecto en nuevas optimizaciones', max_length=10)),
                ('algoritmo_predeterminado', models.CharField(choices=[('ffd', 'First Fit Decreasing (FFD)'), ('best_fit', 'Best Fit'), ('first_fit', 'First Fit')], default='ffd', help_text='Algoritmo de optimización que se usará por defecto', max_length=20)),
                ('margen_corte_predeterminado', models.DecimalField(decimal_places=2, default=Decimal('0.3'), help_text='Margen de corte predeterminado en centímetros', max_digits=5)),
                ('rotacion_automatica_predeterminada', models.BooleanField(default=True, help_text='Permitir rotación automática de piezas por defecto')),
                ('precio_tablero_predeterminado', models.DecimalField(blank=True, decimal_places=2, help_text='Precio por tablero que se usará por defecto (opcional)', max_digits=10, null=True)),
                ('mano_obra_predeterminada', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Costo de mano de obra que se usará por defecto (opcional)', max_digits=10, null=True)),
                ('notificaciones_email', models.BooleanField(default=False, help_text='Recibir notificaciones por correo electrónico')),
                ('notificaciones_pantalla', models.BooleanField(default=True, help_text='Mostrar notificaciones en pantalla')),
                ('email_notificaciones', models.EmailField(blank=True, help_text='Email para recibir notificaciones (opcional, por defecto se usa el email del usuario)', max_length=254, null=True)),
                ('notificar_optimizacion_completada', models.BooleanField(default=True, help_text='Notificar cuando se completa una optimización')),
                ('notificar_presupuesto_creado', models.BooleanField(default=True, help_text='Notificar cuando se crea un presupuesto')),
                ('notificar_proyecto_creado', models.BooleanField(default=True, help_text='Notificar cuando se crea un proyecto')),
                ('notificar_errores', models.BooleanField(default=True, help_text='Notificar cuando hay errores en la optimización')),
                ('puede_crear_plantillas', models.BooleanField(default=True, help_text='Permitir crear y editar plantillas')),
                ('puede_comparar_optimizaciones', models.BooleanField(default=True, help_text='Permitir acceso a herramienta de comparación')),
                ('puede_crear_clientes', models.BooleanField(default=True, help_text='Permitir crear y editar clientes')),
                ('puede_crear_proyectos', models.BooleanField(default=True, help_text='Permitir crear y editar proyectos')),
                ('puede_crear_presupuestos', models.BooleanField(default=True, help_text='Permitir crear y editar presupuestos')),
                ('puede_crear_materiales', models.BooleanField(default=True, help_text='Permitir crear y editar materiales')),
                ('puede_ver_estadisticas', models.BooleanField(default=True, help_text='Permitir acceso a estadísticas')),
                ('puede_ver_historial_costos', models.BooleanField(default=True, help_text='Permitir acceso a historial de costos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('material_predeterminado', models.ForeignKey(blank=True, help_text='Material que se seleccionará por defecto en nuevas optimizaciones', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_con_material_predeterminado', to='cutless.material')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
