# Generated by Django 5.2.8 on 2026-05-29 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='algoritmo_predeterminado',
        ),
    ]
