# Generated by Django 5.2.8 on 2026-10-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_algoritmo_predeterminado'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='preferencias_menu',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
