"""
Django settings para CutLess (paquete de configuración: cutless_project).

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from .environment import configuracion_entorno

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# El desarrollo local es el modo predeterminado. Producción exige variables explícitas.
globals().update(configuracion_entorno(BASE_DIR))

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cutless.apps.CutlessConfig',
    'usuarios',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cutless.middleware.DatabaseHealthCheckMiddleware',  # Verificar BD
]

ROOT_URLCONF = 'cutless_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'cutless' / 'templates'],  # Páginas de error personalizadas
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cutless.context_processors.tutorial_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'cutless_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': Path(os.environ.get('CUTLESS_DB_PATH', BASE_DIR / 'db.sqlite3')),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'es-cl'
TIME_ZONE = 'America/Santiago'
USE_I18N = True
USE_TZ = True
# Solo español habilitado
LANGUAGES = [
    ('es', 'Español'),
]
LOCALE_PATHS = [BASE_DIR / 'locale']


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# STATICFILES_DIRS se elimina porque los archivos estáticos están en las apps
# STATICFILES_DIRS = [
#     BASE_DIR / 'static',
# ]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#redireccionamiento del login, cambiar de ser necesario
LOGIN_REDIRECT_URL = '/cutless/'
LOGOUT_REDIRECT_URL = '/usuarios/login/'
LOGIN_URL = 'usuarios:login'

# Configuración de sesiones para mayor seguridad
# La sesión expira cuando se cierra el navegador (si el navegador lo soporta)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# Tiempo de expiración de la sesión en segundos (30 minutos = 1800 segundos por defecto)
# Los usuarios pueden personalizar esto desde su perfil
SESSION_COOKIE_AGE = 1800  # 30 minutos
# Prevenir acceso a cookies de sesión desde JavaScript (protección XSS)
SESSION_COOKIE_HTTPONLY = True
# SESSION_COOKIE_SECURE se configura según CUTLESS_ENV en environment.py.

MEDIA_URL = '/media/'
MEDIA_ROOT = Path(os.environ.get('CUTLESS_MEDIA_ROOT', BASE_DIR / 'media'))

# SMTP opcional; sin host los mensajes se imprimen en consola para desarrollo.
EMAIL_HOST = os.environ.get('CUTLESS_EMAIL_HOST', '')
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' if EMAIL_HOST else 'django.core.mail.backends.console.EmailBackend'
EMAIL_PORT = int(os.environ.get('CUTLESS_EMAIL_PORT', '587'))
EMAIL_USE_TLS = bool(EMAIL_HOST)
EMAIL_HOST_USER = os.environ.get('CUTLESS_EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('CUTLESS_EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('CUTLESS_DEFAULT_FROM_EMAIL', 'CutLess <noreply@localhost>')
