# Generated by Django 5.2.8 on 2026-05-03 03:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo o razón social', max_length=200)),
                ('rut', models.CharField(blank=True, help_text='RUT o identificación fiscal', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico', max_length=254)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20)),
                ('direccion', models.TextField(blank=True, help_text='Dirección completa')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el cliente')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(help_text='Usuario propietario del cliente', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
                'unique_together': {('usuario', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del material (ej: MDF 18mm, Contrachapado)', max_length=100)),
                ('ancho', models.FloatField(help_text='Ancho del tablero en cm')),
                ('alto', models.FloatField(help_text='Alto del tablero en cm')),
                ('unidad_medida', models.CharField(choices=[('cm', 'Centímetros (cm)'), ('m', 'Metros (m)'), ('in', 'Pulgadas (in)'), ('ft', 'Pies (ft)')], default='cm', help_text='Unidad de medida para mostrar', max_length=2)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, help_text='Precio por tablero (opcional)', max_digits=10, null=True)),
                ('es_predefinido', models.BooleanField(default=False, help_text='Si es True, es un material del sistema (no se puede eliminar)')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional del material')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario propietario. Null para materiales predefinidos del sistema.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['-es_predefinido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Optimizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ancho_tablero', models.FloatField()),
                ('alto_tablero', models.FloatField()),
                ('unidad_medida', models.CharField(choices=[('cm', 'Centímetros (cm)'), ('m', 'Metros (m)'), ('in', 'Pulgadas (in)'), ('ft', 'Pies (ft)')], default='cm', help_text='Unidad de medida usada por el usuario', max_length=2)),
                ('piezas', models.TextField(help_text='Listado de piezas en formato ancho,alto,cantidad')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='optimizaciones/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('aprovechamiento_total', models.FloatField(default=0)),
                ('favorito', models.BooleanField(default=False)),
                ('permitir_rotacion', models.BooleanField(default=True, help_text='Permitir rotación automática de piezas 90°')),
                ('margen_corte', models.FloatField(default=0.3, help_text='Margen de corte (kerf) en cm (guardado internamente). El valor se ingresa en mm.')),
                ('precio_tablero', models.DecimalField(blank=True, decimal_places=2, help_text='Precio por tablero usado en esta optimización', max_digits=10, null=True)),
                ('mano_obra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo de mano de obra (opcional)', max_digits=10)),
                ('num_tableros', models.IntegerField(default=0, help_text='Número de tableros utilizados (calculado automáticamente)')),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente asociado a esta optimización (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cutless.cliente')),
                ('material', models.ForeignKey(blank=True, help_text='Material/tablero utilizado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cutless.material')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del proyecto', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del proyecto')),
                ('fecha_inicio', models.DateField(blank=True, help_text='Fecha de inicio del proyecto', null=True)),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha de finalización estimada', null=True)),
                ('estado', models.CharField(choices=[('planificacion', 'Planificación'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='planificacion', help_text='Estado actual del proyecto', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente asociado al proyecto (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cutless.cliente')),
                ('usuario', models.ForeignKey(help_text='Usuario propietario del proyecto', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número único del presupuesto (ej: PRE-2025-001)', max_length=50, unique=True)),
                ('precio_tablero', models.DecimalField(decimal_places=2, help_text='Precio por tablero usado en el presupuesto', max_digits=10)),
                ('mano_obra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo de mano de obra', max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, help_text='Costo total del presupuesto', max_digits=10)),
                ('fecha_validez', models.DateField(help_text='Fecha hasta la cual el presupuesto es válido')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('vencido', 'Vencido')], default='borrador', help_text='Estado del presupuesto', max_length=20)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales para el cliente')),
                ('pdf', models.FileField(blank=True, help_text='PDF generado del presupuesto', null=True, upload_to='presupuestos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente al que se envía el presupuesto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cutless.cliente')),
                ('optimizaciones', models.ManyToManyField(help_text='Optimizaciones asociadas al presupuesto', related_name='presupuestos', to='cutless.optimizacion')),
                ('usuario', models.ForeignKey(help_text='Usuario propietario del presupuesto', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, help_text='Proyecto asociado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cutless.proyecto')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='optimizacion',
            name='proyecto',
            field=models.ForeignKey(blank=True, help_text='Proyecto al que pertenece esta optimización (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cutless.proyecto'),
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la plantilla', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la plantilla')),
                ('categoria', models.CharField(choices=[('cocina', 'Cocina'), ('muebles', 'Muebles'), ('puertas', 'Puertas'), ('ventanas', 'Ventanas'), ('estantes', 'Estantes'), ('otros', 'Otros')], default='otros', help_text='Categoría de la plantilla', max_length=20)),
                ('ancho_tablero', models.FloatField(help_text='Ancho del tablero en cm')),
                ('alto_tablero', models.FloatField(help_text='Alto del tablero en cm')),
                ('unidad_medida', models.CharField(choices=[('cm', 'Centímetros (cm)'), ('m', 'Metros (m)'), ('in', 'Pulgadas (in)'), ('ft', 'Pies (ft)')], default='cm', help_text='Unidad de medida', max_length=2)),
                ('piezas', models.TextField(help_text='Listado de piezas en formato nombre,ancho,alto,cantidad')),
                ('permitir_rotacion', models.BooleanField(default=True, help_text='Permitir rotación automática')),
                ('margen_corte', models.FloatField(default=0.3, help_text='Margen de corte en cm')),
                ('es_predefinida', models.BooleanField(default=False, help_text='Si es True, es una plantilla del sistema (no se puede eliminar)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario propietario. Null para plantillas predefinidas del sistema.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla',
                'verbose_name_plural': 'Plantillas',
                'ordering': ['-es_predefinida', 'categoria', 'nombre'],
                'unique_together': {('usuario', 'nombre')},
            },
        ),
    ]
