# Generated by Django 5.2.8 on 2026-05-29 23:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutless', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='numero',
            field=models.CharField(help_text='Número del presupuesto, único por usuario (ej: PRE-2025-0001)', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='presupuesto',
            unique_together={('usuario', 'numero')},
        ),
    ]
