# Generated by Django 5.2.8 on 2026-05-29 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutless', '0002_presupuesto_numero_por_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizacion',
            name='area_usada_total',
            field=models.FloatField(blank=True, help_text='Área total utilizada en cm² (snapshot al generar resultado)', null=True),
        ),
        migrations.AddField(
            model_name='optimizacion',
            name='desperdicio_total',
            field=models.FloatField(blank=True, help_text='Desperdicio total en cm² (snapshot al generar resultado)', null=True),
        ),
        migrations.AddField(
            model_name='optimizacion',
            name='resultado_extra',
            field=models.JSONField(blank=True, default=dict, help_text='Metadatos extra del resultado (piezas no colocadas, totales, etc.)'),
        ),
        migrations.AddField(
            model_name='optimizacion',
            name='resultado_generado',
            field=models.BooleanField(default=False, help_text='Indica si las imágenes y estadísticas del resultado están persistidas'),
        ),
        migrations.AddField(
            model_name='optimizacion',
            name='resultado_generado_en',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se persistió el resultado completo', null=True),
        ),
        migrations.CreateModel(
            name='TableroOptimizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('imagen', models.ImageField(upload_to='optimizaciones/tableros/')),
                ('area_usada', models.FloatField(help_text='Área usada en cm²')),
                ('desperdicio', models.FloatField(help_text='Desperdicio en cm²')),
                ('porcentaje_uso', models.FloatField(help_text='Porcentaje de aprovechamiento del tablero')),
                ('num_piezas', models.PositiveIntegerField(default=0)),
                ('optimizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tableros', to='cutless.optimizacion')),
            ],
            options={
                'verbose_name': 'Tablero de optimización',
                'verbose_name_plural': 'Tableros de optimización',
                'ordering': ['numero'],
                'unique_together': {('optimizacion', 'numero')},
            },
        ),
    ]
