# Generated by Django 5.2.7 on 2025-10-21 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Optimizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ancho_tablero', models.IntegerField()),
                ('alto_tablero', models.IntegerField()),
                ('piezas', models.TextField(help_text='Listado de piezas en formato ancho,alto,cantidad')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='optimizaciones/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='optimizaciones_pdfs/')),
                ('aprovechamiento_total', models.FloatField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
