# Generated by Django 5.2.8 on 2025-12-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opticut', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optimizacion',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='optimizacion',
            name='favorito',
            field=models.BooleanField(default=False, help_text='Marcar como favorito'),
        ),
    ]
