# Generated by Django 5.2.8 on 2025-12-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opticut', '0002_alter_optimizacion_options_optimizacion_favorito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optimizacion',
            options={},
        ),
        migrations.AddField(
            model_name='optimizacion',
            name='unidad_medida',
            field=models.CharField(choices=[('cm', 'Centímetros (cm)'), ('m', 'Metros (m)'), ('in', 'Pulgadas (in)'), ('ft', 'Pies (ft)')], default='cm', help_text='Unidad de medida usada por el usuario', max_length=2),
        ),
        migrations.AlterField(
            model_name='optimizacion',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
    ]
