# Generated by Django 5.2.8 on 2025-12-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opticut', '0003_alter_optimizacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizacion',
            name='margen_corte',
            field=models.FloatField(default=0.3, help_text='Margen de corte (kerf) en cm. Típicamente 0.2-0.4 cm (2-4mm)'),
        ),
        migrations.AddField(
            model_name='optimizacion',
            name='permitir_rotacion',
            field=models.BooleanField(default=True, help_text='Permitir rotación automática de piezas 90°'),
        ),
        migrations.AlterField(
            model_name='optimizacion',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
