# Generated by Django 5.2.8 on 2025-12-19 23:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opticut', '0004_optimizacion_margen_corte_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizacion',
            name='mano_obra',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo de mano de obra (opcional)', max_digits=10),
        ),
        migrations.AddField(
            model_name='optimizacion',
            name='num_tableros',
            field=models.IntegerField(default=0, help_text='Número de tableros utilizados (calculado automáticamente)'),
        ),
        migrations.AddField(
            model_name='optimizacion',
            name='precio_tablero',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio por tablero usado en esta optimización', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='optimizacion',
            name='margen_corte',
            field=models.FloatField(default=0.3, help_text='Margen de corte (kerf) en cm (guardado internamente). El valor se ingresa en mm.'),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del material (ej: MDF 18mm, Contrachapado)', max_length=100)),
                ('ancho', models.FloatField(help_text='Ancho del tablero en cm')),
                ('alto', models.FloatField(help_text='Alto del tablero en cm')),
                ('unidad_medida', models.CharField(choices=[('cm', 'Centímetros (cm)'), ('m', 'Metros (m)'), ('in', 'Pulgadas (in)'), ('ft', 'Pies (ft)')], default='cm', help_text='Unidad de medida para mostrar', max_length=2)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, help_text='Precio por tablero (opcional)', max_digits=10, null=True)),
                ('es_predefinido', models.BooleanField(default=False, help_text='Si es True, es un material del sistema (no se puede eliminar)')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional del material')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario propietario. Null para materiales predefinidos del sistema.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['-es_predefinido', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='optimizacion',
            name='material',
            field=models.ForeignKey(blank=True, help_text='Material/tablero utilizado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='opticut.material'),
        ),
    ]
