# Generated by Django 5.2.8 on 2025-12-19 23:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opticut', '0005_optimizacion_mano_obra_optimizacion_num_tableros_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo o razón social', max_length=200)),
                ('rut', models.CharField(blank=True, help_text='RUT o identificación fiscal', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico', max_length=254)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20)),
                ('direccion', models.TextField(blank=True, help_text='Dirección completa')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el cliente')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(help_text='Usuario propietario del cliente', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
                'unique_together': {('usuario', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='optimizacion',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente asociado a esta optimización (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='opticut.cliente'),
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del proyecto', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del proyecto')),
                ('fecha_inicio', models.DateField(blank=True, help_text='Fecha de inicio del proyecto', null=True)),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha de finalización estimada', null=True)),
                ('estado', models.CharField(choices=[('planificacion', 'Planificación'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='planificacion', help_text='Estado actual del proyecto', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente asociado al proyecto (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='opticut.cliente')),
                ('usuario', models.ForeignKey(help_text='Usuario propietario del proyecto', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número único del presupuesto (ej: PRE-2025-001)', max_length=50, unique=True)),
                ('precio_tablero', models.DecimalField(decimal_places=2, help_text='Precio por tablero usado en el presupuesto', max_digits=10)),
                ('mano_obra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo de mano de obra', max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, help_text='Costo total del presupuesto', max_digits=10)),
                ('fecha_validez', models.DateField(help_text='Fecha hasta la cual el presupuesto es válido')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('vencido', 'Vencido')], default='borrador', help_text='Estado del presupuesto', max_length=20)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales para el cliente')),
                ('pdf', models.FileField(blank=True, help_text='PDF generado del presupuesto', null=True, upload_to='presupuestos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente al que se envía el presupuesto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='opticut.cliente')),
                ('optimizacion', models.ForeignKey(help_text='Optimización asociada al presupuesto', on_delete=django.db.models.deletion.CASCADE, to='opticut.optimizacion')),
                ('proyecto', models.ForeignKey(blank=True, help_text='Proyecto asociado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='opticut.proyecto')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='optimizacion',
            name='proyecto',
            field=models.ForeignKey(blank=True, help_text='Proyecto al que pertenece esta optimización (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='opticut.proyecto'),
        ),
    ]
