# Generated by Django 5.2.8 on 2025-12-19 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opticut', '0006_cliente_optimizacion_cliente_proyecto_presupuesto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la plantilla', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la plantilla')),
                ('categoria', models.CharField(choices=[('cocina', 'Cocina'), ('muebles', 'Muebles'), ('puertas', 'Puertas'), ('ventanas', 'Ventanas'), ('estantes', 'Estantes'), ('otros', 'Otros')], default='otros', help_text='Categoría de la plantilla', max_length=20)),
                ('ancho_tablero', models.FloatField(help_text='Ancho del tablero en cm')),
                ('alto_tablero', models.FloatField(help_text='Alto del tablero en cm')),
                ('unidad_medida', models.CharField(choices=[('cm', 'Centímetros (cm)'), ('m', 'Metros (m)'), ('in', 'Pulgadas (in)'), ('ft', 'Pies (ft)')], default='cm', help_text='Unidad de medida', max_length=2)),
                ('piezas', models.TextField(help_text='Listado de piezas en formato nombre,ancho,alto,cantidad')),
                ('permitir_rotacion', models.BooleanField(default=True, help_text='Permitir rotación automática')),
                ('margen_corte', models.FloatField(default=0.3, help_text='Margen de corte en cm')),
                ('es_predefinida', models.BooleanField(default=False, help_text='Si es True, es una plantilla del sistema (no se puede eliminar)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario propietario. Null para plantillas predefinidas del sistema.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla',
                'verbose_name_plural': 'Plantillas',
                'ordering': ['-es_predefinida', 'categoria', 'nombre'],
                'unique_together': {('usuario', 'nombre')},
            },
        ),
    ]
