# Generated by Django 5.2.8 on 2025-12-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opticut', '0007_plantilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimizacion',
            name='alto_tablero',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='optimizacion',
            name='ancho_tablero',
            field=models.FloatField(),
        ),
    ]
