# Generated by Django 5.2.8 on 2025-12-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opticut', '0008_alter_optimizacion_alto_tablero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='optimizacion',
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='optimizaciones',
            field=models.ManyToManyField(help_text='Optimizaciones asociadas al presupuesto', related_name='presupuestos', to='opticut.optimizacion'),
        ),
    ]
