# Generated by Django 5.2.8 on 2025-12-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='tutorial_completado',
            field=models.BooleanField(default=False, help_text='Indica si el usuario ha completado el tutorial inicial'),
        ),
    ]
