# Generated by Django 5.2.8 on 2025-12-20 16:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opticut', '0012_make_presupuesto_usuario_required'),
        ('usuarios', '0002_perfilusuario_tutorial_completado'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='algoritmo_predeterminado',
            field=models.CharField(choices=[('ffd', 'First Fit Decreasing (FFD)'), ('best_fit', 'Best Fit'), ('first_fit', 'First Fit')], default='ffd', help_text='Algoritmo de optimización que se usará por defecto', max_length=20),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='mano_obra_predeterminada',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Costo de mano de obra que se usará por defecto (opcional)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='margen_corte_predeterminado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.3'), help_text='Margen de corte predeterminado en centímetros', max_digits=5),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='material_predeterminado',
            field=models.ForeignKey(blank=True, help_text='Material que se seleccionará por defecto en nuevas optimizaciones', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_con_material_predeterminado', to='opticut.material'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='precio_tablero_predeterminado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio por tablero que se usará por defecto (opcional)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='rotacion_automatica_predeterminada',
            field=models.BooleanField(default=True, help_text='Permitir rotación automática de piezas por defecto'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='unidad_medida_predeterminada',
            field=models.CharField(choices=[('cm', 'Centímetros (cm)'), ('mm', 'Milímetros (mm)'), ('pulgadas', 'Pulgadas (in)')], default='cm', help_text='Unidad de medida que se usará por defecto en nuevas optimizaciones', max_length=10),
        ),
    ]
