# Generated by Django 5.2.8 on 2025-12-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_perfilusuario_algoritmo_predeterminado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='email_notificaciones',
            field=models.EmailField(blank=True, help_text='Email para recibir notificaciones (opcional, por defecto se usa el email del usuario)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='notificaciones_email',
            field=models.BooleanField(default=False, help_text='Recibir notificaciones por correo electrónico'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='notificaciones_pantalla',
            field=models.BooleanField(default=True, help_text='Mostrar notificaciones en pantalla'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='notificar_errores',
            field=models.BooleanField(default=True, help_text='Notificar cuando hay errores en la optimización'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='notificar_optimizacion_completada',
            field=models.BooleanField(default=True, help_text='Notificar cuando se completa una optimización'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='notificar_presupuesto_creado',
            field=models.BooleanField(default=True, help_text='Notificar cuando se crea un presupuesto'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='notificar_proyecto_creado',
            field=models.BooleanField(default=True, help_text='Notificar cuando se crea un proyecto'),
        ),
    ]
