# Generated by Django 5.2.8 on 2025-12-20 22:37

from django.db import migrations, models


def convertir_pulgadas_a_in(apps, schema_editor):
    """Convierte valores antiguos 'pulgadas' a 'in' para compatibilidad"""
    PerfilUsuario = apps.get_model('usuarios', 'PerfilUsuario')
    PerfilUsuario.objects.filter(unidad_medida_predeterminada='pulgadas').update(unidad_medida_predeterminada='in')


def revertir_in_a_pulgadas(apps, schema_editor):
    """Revertir conversión para rollback"""
    PerfilUsuario = apps.get_model('usuarios', 'PerfilUsuario')
    PerfilUsuario.objects.filter(unidad_medida_predeterminada='in').update(unidad_medida_predeterminada='pulgadas')


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfilusuario_email_notificaciones_and_more'),
    ]

    operations = [
        migrations.RunPython(convertir_pulgadas_a_in, revertir_in_a_pulgadas),
        migrations.AlterField(
            model_name='perfilusuario',
            name='unidad_medida_predeterminada',
            field=models.CharField(choices=[('cm', 'Centímetros (cm)'), ('m', 'Metros (m)'), ('mm', 'Milímetros (mm)'), ('in', 'Pulgadas (in)'), ('ft', 'Pies (ft)')], default='cm', help_text='Unidad de medida que se usará por defecto en nuevas optimizaciones', max_length=10),
        ),
    ]
