# Generated by Django 5.2.8 on 2026-03-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_actualizar_unidad_medida_predeterminada'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='tamanio_fuente',
            field=models.CharField(choices=[('small', 'Pequeño'), ('normal', 'Normal'), ('large', 'Grande'), ('xlarge', 'Extra Grande')], default='normal', help_text='Tamaño de fuente preferido para facilitar la lectura', max_length=10),
        ),
    ]
