# Generated by Django 5.2.8 on 2026-03-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_perfilusuario_tamanio_fuente'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('admin', 'Administrador')], default='usuario', help_text='Rol del usuario en el sistema', max_length=20),
        ),
    ]
