# Generated by Django 5.2.8 on 2026-03-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_perfilusuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='puede_comparar_optimizaciones',
            field=models.BooleanField(default=True, help_text='Permitir acceso a herramienta de comparación'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='puede_crear_clientes',
            field=models.BooleanField(default=True, help_text='Permitir crear y editar clientes'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='puede_crear_materiales',
            field=models.BooleanField(default=True, help_text='Permitir crear y editar materiales'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='puede_crear_plantillas',
            field=models.BooleanField(default=True, help_text='Permitir crear y editar plantillas'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='puede_crear_presupuestos',
            field=models.BooleanField(default=True, help_text='Permitir crear y editar presupuestos'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='puede_crear_proyectos',
            field=models.BooleanField(default=True, help_text='Permitir crear y editar proyectos'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='puede_ver_estadisticas',
            field=models.BooleanField(default=True, help_text='Permitir acceso a estadísticas'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='puede_ver_historial_costos',
            field=models.BooleanField(default=True, help_text='Permitir acceso a historial de costos'),
        ),
    ]
